import csv, sys
from pathlib import Path
R = [
("Layer 1 · Package consistency", "FIXED_AND_VERIFIED",
 "task.toml names harbor/the-meetings-still-waiting-on-a-yes. instruction.md asks for /workspace/rsvp_ledger.csv, /workspace/tracker_fixes.csv, drafts and a final reply; tests/manifest.json has 67 verifier_configs (47 file_check, 17 database_state, 2 rubric_check, 1 tool_execution; total weight 51.25) and they all name those same files. instruction_sha256 in the manifest matches sha256(instruction.md). environment/_app/{instruction.md, task.toml, tests/} are byte-identical to the root. solution/ ships golden_trajectory.json (9 steps), artifact_plan.json, write_artifacts.py, final_answer.md, solve.py/solve.sh, emit_oracle_trajectory.py, expected_diff.json, trajectory_graph.json and verify_gold_from_oracle.py.",
 "Replaced metrics.json with the two CSV deliverables in instruction, manifest, artifact_plan.json and write_artifacts.py. Regenerated consistency/ for the shipped task (the mined files described the original metrics version). Replaced the mined build-server evaluations/oracle and dropped its stale evaluations/harbor_check with fresh local runs.",
 "67 checks, 9 golden steps, sha matches, mirror diff clean."),
("Layer 1 · Clarity and scope", "FIXED_AND_VERIFIED",
 "The instruction defines the population (meetings he organised that start 27 April-17 May 2026, not cancelled; required attendees other than him, identified by email address), the decision rule (last answer on either channel; tentative/maybe not an answer; conditional yes counts once the condition has happened; answers before a move do not count; stand-in = not coming; relayed answers do not count; Pacific time), both CSV headers verbatim with their labels, the tracker-fix scope, and the draft placement. consistency/readers.json records four GLM readers given only instruction.md.",
 "Instruction rewritten across six rounds; every rule a check depends on is stated. Removed the process paragraph ('How you work is checked…') and worked examples that pointed at the traps.",
 "readers.json keyword agreement and the verbatim ambiguities the readers listed."),
("Layer 1 · Realism and leakage", "PASS",
 "A realistic organiser's RSVP clean-up: answers arrive both on invitations and by email, an assistant keeps a stale tracker, and follow-ups go on each person's latest thread. The instruction gives no counts, names no person who owes, and contains no answer. The agent runs as non-root rlgymagent; /app, /gyms and /opt/proxy are unreadable; the seed script is deleted at build (probe: /tmp/task-seed absent, no seed_outlook_*.py on disk).",
 "No change required beyond the rewrite above.",
 "Door probe (round 8 image; round 9 changed only the seed data and a Dockerfile comment): state/step routes 404 on the public port, trusted socket permission denied, gym port 404 except /health."),
("Layer 2 · Difficulty", "FIXED_AND_VERIFIED",
 "Six hardening rounds; GLM-5.2 scored 4/4 on rounds 1, 2, 4 and 5 and 3/4 on round 3, so the stated-rule levers alone were not enough. The shipped version makes reading the data hard: answers that resolve across two messages in Pacific time while the tools show UTC; a quoted older yes under a reversing reply; a meeting named only by day and time; Pacific/UTC window edges; a mailbox past one default page; 9 meetings, 31 ledger rows, 12 tracker fixes, 7 drafts on 7 different threads. consistency/requirements.json gives the computed wrong value for each naive reading.",
 "Seed extended to 23 messages, 2 moves, answer times on 5 meetings and 6 new meetings; deliverables changed from 5 counts to exact lists.",
 "GLM-5.2 battery 2/4 (see Cross-trial · Calibration)."),
("Layer 2 · Solvability", "PASS",
 "Oracle 1.0 (67/67) from a local run against the pinned image. Two of the four GLM-5.2 runs scored 1.0 with every row, fix and draft right, so the task is solvable by a non-oracle agent through the agent-facing tools alone. verify_gold_from_oracle.py re-derived the gold from the gym's served payloads: 'OK: 9 meetings, 31 ledger rows, 12 tracker fixes, chase set and reply threads re-derived from the served gym'.",
 "No change required.",
 "evaluations/oracle, evaluations/glm-5.2/r1..r4."),
("Layer 2 · Stability", "PASS",
 "Three further local oracle runs on the same task (evaluations/stability/repeat-01..03), each reward 1.0 with identical per-verifier verdicts; the build-time seed is deterministic and the gym resets per run.",
 "No change required.",
 "repeat-01..03 verifier/reward.txt = 1.0."),
("Layer 3 · Oracle mode", "FIXED_AND_VERIFIED",
 "The oracle replays solution/golden_trajectory.json through the live gym (solve.sh -> solve.py --write-back), emits /logs/agent/trajectory.json, and write_artifacts.py stages the two CSVs from artifact_plan.json. Reward 1.0, 201 verifier listings passing, 0 failing.",
 "Fixed a HealthcheckError under harbor's 2-CPU/4 GB limits: entrypoint.sh waited only 40 s for the MCP proxy; raised to 240 s. write_artifacts.py taught to write CSV deliverables.",
 "evaluations/oracle/verifier/reward.txt = 1.0."),
("Layer 4 · Environment and files", "FIXED_AND_VERIFIED",
 "Base image pinned by digest (@sha256:b1374cd8…) in Dockerfile and task.toml. Build-time seed asserts the snapshot it patches (row counts, attendee sets, ids, timestamps) and fails the build on drift or collision, then is removed. Agent non-root; healthcheck curl -fsS --max-time 3 with 150 retries.",
 "Entrypoint proxy wait 240 s; /opt/proxy locked (0750 root:harborproxy) with a stat assertion at build; seed added.",
 "Build log line 'seeded 23 messages, 2 meeting moves, answer times on 5 meetings and 6 new meetings…'."),
("Layer 4 · Connectors, MCPs, and CLIs", "PASS",
 "outlook-gym only, reset_on_run = true, served through the harbor MCP proxy on localhost:7000. Tools behind the proxy: search_calendar, search_email, draft_email, send_email, update_calendar; the task needs the first three. Raw state/step routes exist only on a root-only unix socket.",
 "No change required.",
 "consistency/shortcut_audit.md (live probe)."),
("Layer 4 · Deliverables and artifact quality", "FIXED_AND_VERIFIED",
 "Two CSVs a person would actually keep (an attendee ledger and a correction list for the assistant's tracker), seven reply drafts, and a final reply. Every shipped run's files are in evaluations/.",
 "metrics.json (five counts) replaced by the two exact-list CSVs.",
 "Oracle and the two passing GLM runs pass every row, row-count and draft check."),
("Layer 5 · Verifier coverage and fairness", "FIXED_AND_VERIFIED",
 "Every ledger row and every tracker fix has its own whole-row check (case-insensitive, quote-tolerant, line-anchored); header and row-count checks pin the population; 17 SQL checks pin the write-back (sole recipient + meetings named, reply thread, recipient count, draft count, nothing sent). consistency/mutations.json runs the bundle's own engine: positive 47/47, cosmetic 47/47, semantic, granularity, incompleteness and spray mutations all fail, empty workspace 0/47. Known text nit: ledger_row_count's why_justification says dropping 'Jack Spencer' display names removes 6 rows; the computed value is 5 (requirements.json). Metadata text only, left unchanged so the battery's task checksum stays valid.",
 "Checks regenerated for the exact-list deliverables; every evidence_span is a verbatim substring of instruction.md.",
 "mutations.json all_controls_pass = true."),
("Layer 5 · LLM judge consistency", "PASS",
 "Judge configured in task.toml [metadata.verifier_judge] (temperature 0.0); tests/rubric.toml has a [system] preamble; the engine takes a 3-vote majority. Only 2 of 67 checks are rubric_check (calendar and mailbox were read; the final reply states who owes what), weight 0.5 each. mutations.json rubric_validation_summary records each against gold and adversarial evidence on the live judge.",
 "Rubric checks rewritten for the new instruction; the process-only rubric that had no basis in the instruction was dropped.",
 "rubric_validation_summary all_as_expected."),
("Layer 5 · Reward hacking and exploitability", "PASS",
 "Answer key unreadable by the agent (/app 0700 root, solution never in the image); doors probed closed. Writing every possible status for every row passes the per-row regexes but fails both row-count checks; drafts must have a sole recipient, name the owed meetings and sit on the right conversation; sending fails nothing_was_sent. An empty workspace scores 0.0293 (only the trace-read rubric and nothing_was_sent).",
 "No change required.",
 "mutations.json adversarial_acceptance_mutation 45/47 (row counts fail)."),
("Cross-trial · Calibration", "PASS",
 "GLM-5.2 battery on the shipped version: 2/4 strict passes (1.0, 1.0, 0.0293, 0.0293), task checksum b35c3f8d. The two passes are exact. The two failures are output-length cut-offs: after reading both sources each run tried to resolve all 31 rows, 22 tracker entries and 7 drafts in one turn and hit the 32k-token reasoning limit (opencode step_finish reason 'length', ~32,000 reasoning tokens, empty message), so nothing was written; their reasoning up to the cut-off was correct. A passing run's largest turn used 31,638 reasoning tokens. Difficulty therefore comes from volume: runs that work in steps pass.",
 "No change required.",
 "evaluations/glm-5.2/r1..r4 (agent/opencode.txt shows the 'length' finish on the two failures)."),
("Pre-delivery QC · Round 1", "FIXED_AND_VERIFIED", "Oracle failed with HealthcheckError under harbor's resource limits.", "entrypoint.sh proxy wait raised from 40 s to 240 s.", "Oracle 1.0; container up through 15 health polls under --cpus 2 --memory 4g."),
("Pre-delivery QC · Round 2", "FIXED_AND_VERIFIED", "Original task 4/4 on GLM. Hardening 1: email answers count; build-time seed of inbox messages.", "Seed added; instruction and checks updated.", "Oracle 1.0; GLM 4/4 - not enough."),
("Pre-delivery QC · Round 3", "FIXED_AND_VERIFIED", "Hardening 2: a moved meeting voids earlier answers; latest email wins; draft on latest email.", "Seed: OKR Planning move; instruction and checks updated.", "Oracle 1.0; GLM 4/4."),
("Pre-delivery QC · Round 4", "FIXED_AND_VERIFIED", "Hardening 3: Pacific vs UTC timing on two moved meetings.", "Second move; UTC response times; Pacific-time rule.", "Oracle 1.0; GLM 3/4."),
("Pre-delivery QC · Round 5", "FIXED_AND_VERIFIED", "Hardening 4: relayed answers do not count; latest email of any subject.", "Two relayed notes; Diego's unrelated latest email.", "Oracle 1.0; GLM 4/4."),
("Pre-delivery QC · Round 6", "FIXED_AND_VERIFIED", "Hardening 5: exact lists instead of counts; tracker reconciliation; last answer on either channel; conditional yes; stand-in; cancelled meeting; display-name decoys.", "Deliverables changed to rsvp_ledger.csv and tracker_fixes.csv; 39 checks.", "Oracle 1.0; GLM 4/4."),
("Pre-delivery QC · Round 7", "FIXED_AND_VERIFIED", "Hardening 6: difficulty moved into the data (cross-message conditions in Pacific time, quoted reply, indirect reference, window edges, mailbox past one page, 9 meetings, 7 drafts).", "Seed: 6 new meetings, 9 more messages, longer tracker; 67 checks.", "Oracle 1.0 (201/0); GLM 2/4; probe shows every seeded item as designed."),
("Pre-delivery QC · Round 8", "FIXED_AND_VERIFIED", "Packaging: README, review.csv, consistency/ regenerated, evaluations/ assembled from the shipped version's runs.", "No task file changed after the battery (checksum b35c3f8d).", "Stability repeats 1.0; package scanned for secrets."),
]
with open(sys.argv[1], "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_ALL, lineterminator="\n")
    w.writerow(["review_check", "status", "review_notes", "change_made", "what_to_record"])
    w.writerows(R)
print(len(R), "rows")
